app:
  name: "web_app"
  mode: "dev"
  port: 8081
  version: "v1.0.0"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "000000"
  dbname: "qimiproject"
  max_open_conn: 200
  max_idle_conn: 50

redis:
  host: "192.168.200.3"
  port: 7001
  db: 0
  pool_size: 20

snow:
  start_time: "2022-01-01 00:00:00"
  machine_id: 1